import type { Brand, Category, CuratedSection, Product } from "./types";

/**
 * Placeholder seed data. When a real backend (Firebase/Firestore, etc.) is
 * wired in, this file goes away and lib/api.ts fetches from the DB instead.
 */

export const seedCategories: Category[] = [
  { id: "shirts", name: "Shirts" },
  { id: "shorts", name: "Shorts" },
  { id: "pants", name: "Pants" },
  { id: "hoodies", name: "Hoodies" },
  { id: "others", name: "Others" },
];

export const seedBrands: Brand[] = [
  { id: "nike", name: "Nike" },
  { id: "adidas", name: "Adidas" },
  { id: "uniqlo", name: "Uniqlo" },
  { id: "carhartt", name: "Carhartt" },
];

export const curatedSections: CuratedSection[] = [
  {
    id: "new-arrivals",
    title: "New Arrivals",
    subtitle: "Fresh finds, just racked",
    filter: "new-arrivals",
  },
  {
    id: "discounts",
    title: "On Sale",
    subtitle: "Good catches, better prices",
    filter: "on-sale",
  },
  // Add more sections here later, e.g. "Best Sellers", "Staff Picks".
];

export const seedProducts: Product[] = [
  {
    id: "p1",
    name: "Vintage Swoosh Tee",
    description:
      "Classic 90s-era Nike tee in faded black. Soft, broken-in cotton with a boxy fit. Small fading on the print adds to the vintage character.",
    price: 450,
    discountPrice: 350,
    onSale: true,
    isNewArrival: false,
    categoryId: "shirts",
    brandId: "nike",
    condition: "Good",
    images: ["placeholder:slate", "placeholder:zinc"],
    sizes: ["M", "L"],
    stock: 2,
    tags: ["vintage", "90s", "streetwear"],
    createdAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "p2",
    name: "Trefoil Logo Hoodie",
    description:
      "Adidas Originals pullover hoodie in navy. Heavyweight fleece, kangaroo pocket, embroidered trefoil. Barely worn — practically new.",
    price: 950,
    onSale: false,
    isNewArrival: true,
    categoryId: "hoodies",
    brandId: "adidas",
    condition: "Like New",
    images: ["placeholder:indigo", "placeholder:blue"],
    sizes: ["L", "XL"],
    stock: 1,
    tags: ["hoodie", "fleece"],
    createdAt: "2026-06-28T10:00:00Z",
  },
  {
    id: "p3",
    name: "Airism Oversized Shirt",
    description:
      "Uniqlo Airism cotton-blend shirt in off-white. Breathable, drapey fit — perfect for hot days. No stains or flaws.",
    price: 380,
    onSale: false,
    isNewArrival: true,
    categoryId: "shirts",
    brandId: "uniqlo",
    condition: "Excellent",
    images: ["placeholder:stone"],
    sizes: ["S", "M", "L"],
    stock: 3,
    tags: ["minimal", "summer"],
    createdAt: "2026-06-30T10:00:00Z",
  },
  {
    id: "p4",
    name: "Double Knee Work Pants",
    description:
      "Carhartt double-knee canvas work pants in duck brown. Tough as nails with honest wear. Straight relaxed fit, 32x30.",
    price: 1200,
    discountPrice: 990,
    onSale: true,
    isNewArrival: false,
    categoryId: "pants",
    brandId: "carhartt",
    condition: "Good",
    images: ["placeholder:amber", "placeholder:orange"],
    sizes: ["32"],
    stock: 1,
    tags: ["workwear", "canvas"],
    createdAt: "2026-05-15T10:00:00Z",
  },
  {
    id: "p5",
    name: "Tech Fleece Shorts",
    description:
      "Nike Tech Fleece shorts in heather grey. Tapered fit, zip pockets. Light pilling inside pockets, otherwise excellent.",
    price: 550,
    onSale: false,
    isNewArrival: true,
    categoryId: "shorts",
    brandId: "nike",
    condition: "Excellent",
    images: ["placeholder:gray"],
    sizes: ["M"],
    stock: 2,
    tags: ["athleisure"],
    createdAt: "2026-07-01T10:00:00Z",
  },
  {
    id: "p6",
    name: "Firebird Track Jacket",
    description:
      "Iconic Adidas Firebird track jacket in red with white stripes. Zips smooth, no cracks in the trim. A true statement piece.",
    price: 1100,
    onSale: false,
    isNewArrival: true,
    categoryId: "others",
    brandId: "adidas",
    condition: "Excellent",
    images: ["placeholder:red", "placeholder:rose"],
    sizes: ["M", "L"],
    stock: 1,
    tags: ["track jacket", "retro"],
    createdAt: "2026-07-02T10:00:00Z",
  },
  {
    id: "p7",
    name: "Flannel Check Shirt",
    description:
      "Uniqlo brushed flannel in green/navy check. Cozy and thick, perfect layering piece. Tiny loose thread on hem.",
    price: 420,
    discountPrice: 320,
    onSale: true,
    isNewArrival: false,
    categoryId: "shirts",
    brandId: "uniqlo",
    condition: "Good",
    images: ["placeholder:emerald"],
    sizes: ["M", "L", "XL"],
    stock: 4,
    tags: ["flannel", "layering"],
    createdAt: "2026-04-20T10:00:00Z",
  },
  {
    id: "p8",
    name: "Cargo Utility Shorts",
    description:
      "Carhartt ripstop cargo shorts in olive. Six pockets, relaxed fit. Sun-faded to a perfect washed-out tone.",
    price: 680,
    onSale: false,
    isNewArrival: false,
    categoryId: "shorts",
    brandId: "carhartt",
    condition: "Good",
    images: ["placeholder:lime"],
    sizes: ["32", "34"],
    stock: 2,
    tags: ["cargo", "utility"],
    createdAt: "2026-05-05T10:00:00Z",
  },
  {
    id: "p9",
    name: "Club Fleece Hoodie",
    description:
      "Nike Club fleece hoodie in sail white. Mid-weight, embroidered mini swoosh. One faint mark near the cuff, priced accordingly.",
    price: 850,
    discountPrice: 650,
    onSale: true,
    isNewArrival: false,
    categoryId: "hoodies",
    brandId: "nike",
    condition: "Fair",
    images: ["placeholder:neutral"],
    sizes: ["L"],
    stock: 1,
    tags: ["hoodie", "essentials"],
    createdAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "p10",
    name: "Wide-Fit Chino Pants",
    description:
      "Uniqlo wide-fit chinos in beige. Clean, pressed, zero flaws — looks straight off the rack. 30in waist.",
    price: 590,
    onSale: false,
    isNewArrival: true,
    categoryId: "pants",
    brandId: "uniqlo",
    condition: "Like New",
    images: ["placeholder:yellow"],
    sizes: ["30"],
    stock: 1,
    tags: ["chino", "minimal"],
    createdAt: "2026-06-29T10:00:00Z",
  },
  {
    id: "p11",
    name: "Detroit Chore Jacket",
    description:
      "Carhartt Detroit jacket in washed black canvas with blanket lining. The grail piece — heavy, warm, beautifully worn in.",
    price: 2400,
    onSale: false,
    isNewArrival: true,
    categoryId: "others",
    brandId: "carhartt",
    condition: "Good",
    images: ["placeholder:zinc", "placeholder:stone"],
    sizes: ["L"],
    stock: 1,
    tags: ["jacket", "workwear", "grail"],
    createdAt: "2026-07-03T10:00:00Z",
  },
  {
    id: "p12",
    name: "3-Stripe Track Pants",
    description:
      "Adidas track pants in black with white 3-stripes. Snap buttons down the leg. Elastic waist still strong.",
    price: 720,
    discountPrice: 550,
    onSale: true,
    isNewArrival: false,
    categoryId: "pants",
    brandId: "adidas",
    condition: "Good",
    images: ["placeholder:slate"],
    sizes: ["M", "L"],
    stock: 3,
    tags: ["track pants", "retro"],
    createdAt: "2026-04-01T10:00:00Z",
  },
  {
    id: "p13",
    name: "Graphic Court Tee",
    description:
      "Nike basketball graphic tee in white with red print. Crisp print, zero cracking. Athletic fit.",
    price: 400,
    onSale: false,
    isNewArrival: false,
    categoryId: "shirts",
    brandId: "nike",
    condition: "Excellent",
    images: ["placeholder:rose"],
    sizes: ["S", "M"],
    stock: 5,
    tags: ["graphic", "basketball"],
    createdAt: "2026-02-14T10:00:00Z",
  },
  {
    id: "p14",
    name: "Sweat Shorts Set Piece",
    description:
      "Uniqlo sweat shorts in charcoal. Drawstring waist, deep pockets. Everyday comfort at a steal.",
    price: 300,
    discountPrice: 220,
    onSale: true,
    isNewArrival: false,
    categoryId: "shorts",
    brandId: "uniqlo",
    condition: "Good",
    images: ["placeholder:gray"],
    sizes: ["M", "L"],
    stock: 6,
    tags: ["sweats", "lounge"],
    createdAt: "2026-01-25T10:00:00Z",
  },
  {
    id: "p15",
    name: "Zip-Up Tech Hoodie",
    description:
      "Adidas full-zip hoodie in forest green. Smooth tech fleece, slim fit, YKK zip. Like-new condition.",
    price: 980,
    onSale: false,
    isNewArrival: true,
    categoryId: "hoodies",
    brandId: "adidas",
    condition: "Like New",
    images: ["placeholder:emerald", "placeholder:teal"],
    sizes: ["M"],
    stock: 1,
    tags: ["hoodie", "zip-up"],
    createdAt: "2026-07-04T10:00:00Z",
  },
];
